### ISSUE TITLE
syntax highting in math equation treats some part as italic font

### ISSUE THREAD

**Issue by mickeydonkey** [jonschlinkert/sublime-monokai-extended#61]
![image](https://cloud.githubusercontent.com/assets/12562760/12810939/49f316ea-cb64-11e5-8401-a93512cc7a6f.png)

**Comment by jonschlinkert** [comment]
I believe this is something that is caused by markdown syntax highlighting, and is not related to this package. I'm going to close, but this is an [open pr on sublime-markdown-extended](https://github.com/jonschlinkert/sublime-markdown-extended/pull/148) that might fix this. 

If I'm wrong about where this issue is caused, please let me know and I'd be happy to reopen.
