### ISSUE TITLE
Monokai Light: color in gutter display wrong

### ISSUE THREAD

**Issue by PixelT** [jonschlinkert/sublime-monokai-extended#67]
In Monokai Origin:

![monokai-origin](http://img.prntscr.com/img?url=http://i.imgur.com/mfY8Opp.png)

In Monokai Light:

![monokai-light](http://img.prntscr.com/img?url=http://i.imgur.com/zLph2Jb.png)

I used [Color Highlighter](https://packagecontrol.io/packages/Color%20Highlighter)

**Comment by jonschlinkert** [comment]
what color should they be? They look correct to me.

**Comment by PixelT** [comment]
They should be this same as in first (dark) screen: red, red, red, green
But in Light theme, all colors are black (as in 2 screenshot)

**Comment by jonschlinkert** [comment]
Oh I see, sorry I missed the `light` part of the title. Want to do a pr?

**Comment by PixelT** [comment]
Unfortunately not :)

**Comment by PixelT** [comment]
Unfortunately not

**Comment by simonhaenisch** [comment]
It may be because of line [1211](https://github.com/jonschlinkert/sublime-monokai-extended/blob/fffbf1940b3d8b60018ce15018e28904649e5be6/Monokai%20Extended%20Light.JSON-tmTheme#L1211) in `Monokai-Extended-Light.JSON-tmTheme`. At least that's the color, it's a gutter setting and the settings with `sublimelinter` scope don't exist in any of the other theme files.

**Comment by jonschlinkert** [comment]
> Unfortunately not ;)

Ok, closing
