### ISSUE TITLE
Function names in monokai extended theme

### ISSUE THREAD

**Issue by karolyi** [jonschlinkert/sublime-monokai-extended#69]
Hey,

great color scheme, using it since ages.

There was a former, now closed issue which has reappeared again. The keyword colors for python are busted when selecting "Monokai Extended", the theme with the darker background (my favorite). So here's how it looks:
![image](https://cloud.githubusercontent.com/assets/987055/15990427/51008b14-3092-11e6-85b7-6cf657dfe9c9.png)

And then, with "Monokai Extended Bright":
![image](https://cloud.githubusercontent.com/assets/987055/15990433/68560adc-3092-11e6-88ba-b999759bf73e.png)

This happens with a fresh install to pinpoint the problematic package, no other packages installed. Sublime version 3114.

You can see that the keyword colors are busted. Can I have them back with the cyan color?

Related issue: #58

**Comment by jonschlinkert** [comment]
Sure, create an issue on the sublime text project and ask them to stop changing scopes lol. There are so many scope issues with recent changes in sublime text, I'm not even sure where to start. 

closing since an issue already exists about this https://github.com/jonschlinkert/sublime-monokai-extended/issues/62
