### ISSUE TITLE
Problem with $XXXX hexadecimal numbers

### ISSUE THREAD

**Issue by mojontwins** [jonschlinkert/sublime-monokai-extended#86]
Hello

First of all, my excuses if the issue isn't at all related to monokai extended. I guess it may be as I've been given the advice to use monokai extended to work with markdown. If it's not, apologies.

I'm writing .md documents and I've found a problem whenever I enter a hexadecimal number in the $XXXX format, which is a pretty common practice specially if you are referencing assembly listings (which I am).  Syntax is off from that onwards, I don't know if there's a workaround for this?

Something like "this is a block of text which references something which is located at address $8000 in the CPU address space". Everything goes haywire from the "$" onwards.

[Screenshot](http://www.mojontwins.com/warehouse/markdown-off.PNG)

**Comment by jonschlinkert** [comment]
sorry for the late reply. did you ever find a solution to this? I was not able to reproduce, I tried a bunch of different configurations with this plugin and others and didn't see this happen. My guess is that something before that line is actually the cause of the problem, but it's only manifesting there. 

I'm going to go ahead and close, since it seems like this is something unrelated to this lib, but please feel free to reopen if you have any more info.
